export const PLACES = {
  home: {
    name: '我们的小家',
    subtitle: '柴米油盐，也有你',
    district: '栖居巷',
    color: '#789b85',
    x: 22,
    y: 69,
    activities: ['cook', 'eat', 'tv', 'rest', 'tea', 'water', 'read', 'wash'],
    echo: [0, 1.15],
    player: [0.2, 2.75],
  },
  market: {
    name: '青禾超市',
    subtitle: '挑选晚餐食材',
    district: '生活街',
    color: '#cd786c',
    x: 23,
    y: 26,
    activities: ['shop'],
    echo: [0, 2.5],
    player: [1.1, 2.75],
  },
  cinema: {
    name: '星光电影院',
    subtitle: '并肩看一场电影',
    district: '星光路',
    color: '#8a82ab',
    x: 72,
    y: 25,
    activities: ['movie'],
    echo: [3.5, 2.5],
    player: [4.5, 2.75],
  },
  office: {
    name: '晴川公司',
    subtitle: '一起专注，也一起下班',
    district: '晴川路',
    color: '#6b96b0',
    x: 49,
    y: 18,
    activities: ['work'],
    echo: [0, 2.5],
    player: [1.1, 2.75],
  },
  cafe: {
    name: '转角咖啡馆',
    subtitle: '留一点时间给彼此',
    district: '生活街',
    color: '#bd8a58',
    x: 48,
    y: 58,
    activities: ['coffee'],
    echo: [0, 2.5],
    player: [1.1, 2.75],
  },
  park: {
    name: '河畔公园',
    subtitle: '吹吹风，慢慢走',
    district: '沿河步道',
    color: '#6caa91',
    x: 77,
    y: 69,
    activities: ['stroll'],
    echo: [0, 2.5],
    player: [1.1, 2.75],
  },
};

export const PLACE_OBSTACLES = {
  market: [
    [-5.6, -3.8, 5.6, -2.8],
    [-4.6, -1.8, -2.4, 0.7],
    [1.8, -1.8, 3.6, 0.7],
    [-4.8, 2, -2.2, 3.6],
  ],
  cinema: [
    [-5.6, -3.8, 5.6, -2.9],
    ...[-1.4, 0.5, 2.3].flatMap((z) =>
      [-3, -1.5, 0, 1.5].map((x) => [x - 0.48, z - 0.4, x + 0.48, z + 0.4]),
    ),
  ],
  office: [
    [-5.7, -3.8, -4.6, 0.5],
    [-3.9, -2.7, -1.4, -1.5],
    [1.2, -2.7, 3.7, -1.5],
    [-3.9, 0.2, -1.4, 1.4],
    [1.2, 0.2, 3.7, 1.4],
  ],
  cafe: [
    [-5.7, -3.8, 5.7, -2.6],
    [-3.7, -1.6, -2.3, -0.2],
    [1.8, -1.6, 3.2, -0.2],
    [-3.7, 1.5, -2.3, 2.9],
    [1.8, 1.5, 3.2, 2.9],
  ],
  park: [
    [2.7, -3.8, 5.75, 3.75],
    [-4.8, -2.8, -3.2, -1.2],
    [-4.8, 1.4, -3.2, 3],
    [-1.5, -2.8, 1.5, -2],
  ],
};

export const OUTINGS = {
  shop: {
    place: 'market',
    label: '一起买菜',
    verb: '挑选晚餐食材',
    room: '生鲜区',
    duration: 25,
    echo: [-3.4, 1.25],
    player: [-2.4, 1.25],
    line: '番茄很新鲜呢。再挑一点你爱吃的，晚餐就有着落啦。',
    memory: '一起逛了青禾超市，拎着挑好的食材和便当回家。',
    ending: '买好啦，还挑了两份便当。今天的晚餐不用发愁了。',
  },
  movie: {
    place: 'cinema',
    label: '一起看电影',
    verb: '观看星光短片',
    room: '一号影厅',
    duration: 38,
    echo: [-1.5, -0.75],
    player: [0, -0.75],
    line: '票在这里，我们坐一起。灯暗下来的时候，故事就开始了。',
    memory: '在星光电影院并肩看了一场电影，散场后还在聊喜欢的镜头。',
    ending: '最后那个镜头真好。和你一起看的电影，我会记得久一点。',
  },
  work: {
    place: 'office',
    label: '一起专注',
    verb: '整理项目方案',
    room: '协作工位',
    duration: 32,
    echo: [-3, -1],
    player: [-2, -1],
    line: '这份方案我们分着做吧。忙完这一小段，就一起休息。',
    memory: '在晴川公司的工位上一起整理方案，把普通工作日过得有了盼头。',
    ending: '这一部分完成啦！伸个懒腰，我们下班去走走吧。',
  },
  coffee: {
    place: 'cafe',
    label: '喝杯咖啡',
    verb: '分享咖啡与甜点',
    room: '窗边座位',
    duration: 22,
    echo: [-3.9, -0.9],
    player: [-2.1, -0.9],
    line: '点了两杯热咖啡，还有一块小蛋糕。今天的事，慢慢讲给我听吧。',
    memory: '坐在转角咖啡馆的窗边，分享咖啡、小蛋糕和一天的心事。',
    ending: '连杯底都还是暖的。歇过这一会儿，又有精神了。',
  },
  stroll: {
    place: 'park',
    label: '河畔散步',
    verb: '沿着河岸散步',
    room: '沿河步道',
    duration: 30,
    echo: [0.8, -0.5],
    player: [1.8, -0.5],
    line: '河边的风刚刚好。没有急着要去的地方，就这样慢慢走吧。',
    memory: '沿着河畔一起散步，听水声，看树影，把脚步放慢了一点。',
    ending: '绕了一小圈，心情轻了好多。下次也一起出来吹风吧。',
  },
};
